
language: cpp

sudo: required

dist: trusty

before_install:
  - sudo apt-get install libboost-all-dev

install:
  # empty -- all headers

script:
  - cd test-suite && g++ -I.. -o quantlibtestsuite quantlibtestsuite.cpp && ./quantlibtestsuite --log-level=message

notifications:
  email:
    on_success: change
    on_failure: change
  